### ISSUE TITLE
Changing between program and manual mode

### ISSUE THREAD

**Issue by pdemarco925** [deHugo/icomfort-js#1]
Great work. I've been working on a homebridge plugin that leverages your project. 

I have one question. Have you been able to use setThermostatInfo to move the iComfort between program and manual modes? If I'm in manual mode setting the Operation_Mode allows me to switch between heat only / cool only / heat or cool and off. But if I try to toggle the Program_Schedule_Mode between 0 and 1 nothing seems to happen. Just curious if you've used setThermostatInfo for more than just modifying the temperatures.

Thanks.

**Comment by danielmcq** [comment]
I haven't got the mode to switch yet. I have been distracted with some other things, but the last time I was working on this I had added some WSDL files to the project which reference a bunch of other functionality that I haven't had a chance to look in to yet.

I think with just a little bit of time I could figure out how to get the program mode to switch. I'll try to get back to you within the next day or two.

**Comment by danielmcq** [comment]
I have updated the module to version 1.2.0. The client now has a method called `setProgramMode`. Unfortunately, the data it needs passed requires many params, but the good news is it allows you to set the program schedule mode, program schedule, fan mode, operation mode, and cool and heat points all at once!  I documented it here https://github.com/deHugo/icomfort-js#setprogrammodedata.

**Comment by pdemarco925** [comment]
Thanks!
