### ISSUE TITLE
Supported iComfort Thermostat models?

### ISSUE THREAD

**Issue by GaryOkie** [deHugo/icomfort-js#8]
Please confirm what iComfort models are supported.    There is a lower-end "iComfort WiFi" model which I understand may use a different API than the upper end wifi-enabled models (S30, E30, M30 and others).

I had asked @pdemarco925 this same question on his Lennox-iComfort repo, but it doesn't appear to be active any longer.

Thanks for clarifying!

**Comment by danielmcq** [comment]
Hey @GaryOkie! I know for sure it works with the model that I have, which I can’t remember off of the top of my head at this moment. I can update later when I’m home and am able to verify the model of thermostat that I have. 

However, if you already use the www.myicomfort.com to interact with your thermostat, this module should work. It uses endpoints from that site to update the state of your thermostat.

**Comment by GaryOkie** [comment]
Hi @Danielmcq - thanks for the reply.   I tried to login to the myicomfort.com site, but it would not accept my credentials.   It turns out that the myicomfort site appears to be ONLY for the iComfort WiFi model, not the iComfort x30 series which are also advanced Wi-Fi thermostats.    The alternative site I use is [Lennoxicomfort.com](Lennoxicomfort.com).

How crazy it is for Lennox to have two completely different web sites, separate accounts, and different API's for their smart thermostats.
